Repository microsoft/pxt-microbit, pull requests merged in 2018-09, with the labels that each got.

#1208 Web usb error handling
  editor/extension.ts
  package-lock.json
Labels: Do Not Merge

#1234 add Imagimaker Magisheild
  docs/packages.md
  targetconfig.json
Labels: port to v1

#1280 Migrate term 'package' to 'extension'
  docs/SUMMARY.md
  docs/about.md
  docs/docs.md
  docs/extensions.md
  docs/extensions/approval.md
  docs/extensions/build-your-own.md
  docs/open-source.md
  docs/packages/build-your-own.md
  docs/projects/rc-car/code.md
Labels: v1
